<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2023 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 *
 */ ?>

<?php $_product = $block->getProduct(); ?>

<?php $buttonTitle = __('Add to Cart'); ?>

<?php if ($_product->isSaleable()): ?>

    <div class="box-tocart">
        <div class="fieldset">

            <?php if ($block->shouldRenderQuantity()): ?>

                <div class="field qty">
                    <label class="label" for="qty"><span><?= /* @escapeNotVerified */
                            __('Qty') ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               value="<?= /* @escapeNotVerified */
                               $block->getProductDefaultQty() * 1 ?>"
                               title="<?= /* @escapeNotVerified */
                               __('Qty') ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                </div>

            <?php endif; ?>

            <div class="actions">
                <button  type="submit"
                        title="<?= /* @escapeNotVerified */
                        $buttonTitle ?>"
                        class="action primary tocartnewcolor"
                        id="product-addtocart-button">
                    <span><?= /* @escapeNotVerified */
                        $buttonTitle ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>

<?php endif; ?>

<?php if ($block->isRedirectToCartEnabled()) : ?>

    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "Magento_Catalog/product/view/validation": {
                    "radioCheckboxClosest": ".nested"
                }
            }
        }
    </script>

<?php else : ?>

    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "Magento_Catalog/js/validate-product": {}
            }
        }
    </script>

<?php endif; ?>

<div id="popup-modal">
    This is Test JS
</div>

<script type="text/javascript">
    require([
        'jquery',
        'Magento_Ui/js/modal/modal',
        'Magento_Customer/js/customer-data',
    ], function ($, modal, customerData) {

        /**
         * Clear cart function
         */
        function clearCart() {
            $.ajax({
                type: "POST",
                url: "/advancedcheckout/index/clearcart",
                success: function (response) {
                    var sections = ['cart'];
                    customerData.invalidate(sections);
                    customerData.reload(sections, true);
                    if (response.success) {
                        $("#popup-modal").modal("closeModal");
                    }
                    window.location.reload();
                },
                error: function (xhr, status, error) {
                    alert(error);
                }
            });
        }

        var options = {
            type: 'popup',
            title: $.mage.__('Add to Cart Warning'),
            responsive: true,
            innerScroll: true,
            buttons: [
                {
                    text: $.mage.__('Clear Cart'),
                    class: 'clear_cart_btn',
                    click: function () {
                        clearCart()
                    }
                },
                {
                    text: $.mage.__('Proceed to Checkout'),
                    class: 'proceed_to_checkout_btn',
                    click: function () {
                        window.location.href = '/checkout/';
                    }
                }
            ]
        };
        modal(options, $('#popup-modal'));
    })
</script>
